fix: resolve version comparison logic

diff --git a/.github/workflows/sing-box.yml b/.github/workflows/sing-box.yml
--- a/.github/workflows/sing-box.yml
+++ b/.github/workflows/sing-box.yml
@@ -1,16 +1,17 @@
-name: 'Build Sing-box image'
+name: 'Build and Publish Sing-box'
 
 on:
-  workflow_dispatch:
   schedule:
     - cron: '0 16 * * *'
+  workflow_dispatch:
 
 jobs:
   build:
-    name: 'Build Sing-box image'
+    name: 'Build and Publish Sing-box'
     runs-on: ubuntu-latest
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
 
     steps:
       - name: 'Check out repository'
@@ -18,44 +19,44 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: 'Contrast Sing-box version'
+      - name: 'Fetch Versions and Determine Build'
         run: |
-          LATEST_VERSION=$(curl -Lsk "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | jq -r '.tag_name' | sed 's/^v//')
-          CURRENT_VERSION=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/sing-box/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^latest$' | sort -Vr | head -n 1 || echo "")
-          if [ -z "$LATEST_VERSION" ]; then
-            echo "Error: Failed to obtain the latest version!" && exit 1
-          fi
-          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
-          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
-          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || [[ -z "$CURRENT_VERSION" ]]; then
-            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
-          else
-            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
+          SINGBOX_CVER=$(curl -fsSL "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USERNAME }}/sing-box/tags" 2>/dev/null | \
+            jq -r ".results // [] | .[].name" | grep -v '^latest$' | sort -Vr | head -n1 || echo "") && \
+          SINGBOX_LVER=$(curl -fsSL "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | awk -F '["v]' '/tag_name/{print $5}') && \
+          if [[ -z "$SINGBOX_LVER" ]]; then \
+            echo 'Error: Required parameters cannot be empty.' && exit 1; \
+          fi && \
+          echo "SINGBOX_LVER=${SINGBOX_LVER}" >> $GITHUB_ENV && \
+          echo "SINGBOX_CVER=${SINGBOX_CVER}" >> $GITHUB_ENV && \
+          if [[ "$(echo -e "${{ env.SINGBOX_LVER }}\n${{ env.SINGBOX_CVER }}" | sort -V | head -n1)" != "${{ env.SINGBOX_LVER }}" ]] || \
+            [[ -z "${{ env.SINGBOX_CVER }}" ]]; then \
+            echo "IS_RENEW=1" >> $GITHUB_ENV; \
           fi
 
       - name: 'Set up Docker QEMU'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-qemu-action@v3.6.0
 
       - name: 'Set up Docker Buildx'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-buildx-action@v3.10.0
 
       - name: 'Login to DockerHub'
-        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/login-action@v3.4.0
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ env.DOCKER_USERNAME }}
+          password: ${{ env.DOCKER_PASSWORD }}
 
-      - name: 'Build and push Sing-box image'
-        if: ${{ env.BUILD_IMAGE == 'true' || github.event_name == 'workflow_dispatch' }}
+      - name: 'Build and Push Sing-box image'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6.15.0
         with:
           context: "{{ defaultContext }}:fun/sing-box"
           file: Dockerfile
           push: true
           tags: |
-            "${{ env.DOCKER_USERNAME }}/sing-box:${{ env.LATEST_VERSION }}"
+            "${{ env.DOCKER_USERNAME }}/sing-box:${{ env.SINGBOX_LVER }}"
             "${{ env.DOCKER_USERNAME }}/sing-box:latest"
           platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/s390x
