feat: ensure multi-condition build triggering

diff --git a/.github/workflows/sing-box.yml b/.github/workflows/sing-box.yml
--- a/.github/workflows/sing-box.yml
+++ b/.github/workflows/sing-box.yml
@@ -21,16 +21,13 @@ jobs:
       - name: 'Contrast Sing-box version'
         run: |
           LATEST_VERSION=$(curl -Lsk "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | jq -r '.tag_name' | sed 's/^v//')
-          CURRENT_VERSION=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/sing-box/tags" | jq -r '.results[].name' | grep -v '^latest$' | sort -V -r | head -n 1)
-
-          if [ -z "$LATEST_VERSION" ] && [ -z "$CURRENT_VERSION" ]; then
-            echo "ERROR: Failed to obtain the latest version or current version number, please check the URL!" && exit 1
+          CURRENT_VERSION=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/sing-box/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^latest$' | sort -Vr | head -n 1 || echo "")
+          if [ -z "$LATEST_VERSION" ]; then
+            echo "Error: Failed to obtain the latest version!" && exit 1
           fi
-
           echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
           echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
-
-          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]]; then
+          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || [[ -z "$CURRENT_VERSION" ]]; then
             echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
           else
             echo "BUILD_IMAGE=false" >> $GITHUB_ENV
