feat: multiple trigger conditions and optimize version check logic

diff --git a/.github/workflows/sing-box.yml b/.github/workflows/sing-box.yml
--- a/.github/workflows/sing-box.yml
+++ b/.github/workflows/sing-box.yml
@@ -1,4 +1,4 @@
-name: Build Sing-box image
+name: 'Build Sing-box image'
 
 on:
   workflow_dispatch:
@@ -7,68 +7,58 @@ on:
 
 jobs:
   build:
+    name: 'Build Sing-box image'
     runs-on: ubuntu-latest
-    name: "Build Sing-box image"
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 
     steps:
-      - name: Check out repository
+      - name: 'Check out repository'
         uses: actions/checkout@v4.2.2
         with:
           fetch-depth: 0
 
-      - name: Set up Docker QEMU
-        uses: docker/setup-qemu-action@v3.4.0
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.8.0
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v3.3.0
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: Contrast Sing-box version
+      - name: 'Contrast Sing-box version'
         run: |
           LATEST_VERSION=$(curl -Lsk "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | jq -r '.tag_name' | sed 's/^v//')
           CURRENT_VERSION=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/sing-box/tags" | jq -r '.results[].name' | grep -v '^latest$' | sort -V -r | head -n 1)
 
           if [ -z "$LATEST_VERSION" ] && [ -z "$CURRENT_VERSION" ]; then
-              echo "ERROR: Failed to obtain the latest version or current version number, please check the URL!" && exit 1
+            echo "ERROR: Failed to obtain the latest version or current version number, please check the URL!" && exit 1
           fi
 
           echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
           echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
 
           if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]]; then
-              echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
+            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
           else
-              echo "BUILD_IMAGE=false" >> $GITHUB_ENV
+            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
           fi
 
-      - name: Build and push Sing-box image
-        if: env.BUILD_IMAGE == 'true'
+      - name: 'Set up Docker QEMU'
+        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        uses: docker/setup-qemu-action@v3.5.0
+
+      - name: 'Set up Docker Buildx'
+        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        uses: docker/setup-buildx-action@v3.10.0
+
+      - name: 'Login to DockerHub'
+        if: ${{ env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch' }}
+        uses: docker/login-action@v3.4.0
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: 'Build and push Sing-box image'
+        if: ${{ env.BUILD_IMAGE == 'true' || github.event_name == 'workflow_dispatch' }}
         uses: docker/build-push-action@v6.11.0
         with:
-          context: "{{defaultContext}}:fun/sing-box"
+          context: "{{ defaultContext }}:fun/sing-box"
           file: Dockerfile
           push: true
           tags: |
             "${{ env.DOCKER_USERNAME }}/sing-box:${{ env.LATEST_VERSION }}"
             "${{ env.DOCKER_USERNAME }}/sing-box:latest"
           platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/s390x
-
-  # sendmessage:
-  #   runs-on: ubuntu-latest
-  #   name: "Send message"
-  #   needs: build
-
-  #   steps:
-  #     - name: Send success message to Telegram
-  #       if: success()
-  #       uses: appleboy/telegram-action@v1.0.1
-  #       with:
-  #         to: ${{ secrets.TELEGRAM_TO }}
-  #         token: ${{ secrets.TELEGRAM_TOKEN }}
